### ISSUE TITLE
(Back) Finish Map Server

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-mapserver#1]
To Do
- [ ] Api.ts => createStyle(), line 258, Throw `not found` error
- [ ] Api.ts => listStyles(), line 282, `TODO: Limit number of returned entries with getStream options.maxBuffer`
- [ ] Api.ts => uncompositeStyle(), line 335: `TODO: Mapbox styles are sometimes served with sources combined into a single "composite" source. Since core Mapbox sources (e.g. streets, satellite, outdoors etc) can appear in several different styles, this function should extract them from the composite style and adjust the style layers to point to the original source, not the composite. This will save downloading Mapbox sources multiple times for each style they appear in.`
- [ ] Api.ts => init(), line 355 => `TODO: Watch dirs for user-added files? Maybe separate user dir from these data dirs, to avoid users moving mbtiles internally managed here.`

Points : 8

**Comment by gmaclennan** [comment]
> To Do
> 
> * [ ]  Api.ts => createStyle(), line 258, Throw `not found` error

I don't think this is a todo. This is a description of the current behaviour, which I think is ok.

> * [ ]  Api.ts => listStyles(), line 282, `TODO: Limit number of returned entries with getStream options.maxBuffer`

This is not important for v1. Only becomes an issue with thousands of styles.

> * [ ]  Api.ts => uncompositeStyle(), line 335: `TODO: Mapbox styles are sometimes served with sources combined into a single "composite" source. Since core Mapbox sources (e.g. streets, satellite, outdoors etc) can appear in several different styles, this function should extract them from the composite style and adjust the style layers to point to the original source, not the composite. This will save downloading Mapbox sources multiple times for each style they appear in.`

I think we can skip this for v1

> * [ ]  Api.ts => init(), line 355 => `TODO: Watch dirs for user-added files? Maybe separate user dir from these data dirs, to avoid users moving mbtiles internally managed here.`

I think maybe skip this for now. Instead users need to explicitly import mbtiles.

> 
> Points : 8

**Comment by ErikSin** [comment]
Closing this issue as Gregor has broken down the other tasks that should take priority.
