### ISSUE TITLE
Create Mapeo-Server Sqlite Schema

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-mapserver#14]
In an effort to maintain less dependencies, we would like to get rid of leveldb and replace it with a SQLite DB.

### To Do:
- [ ] Create schema
- [ ] Create an ERD
- [ ] Create SQLite db, with approriate schema, in Map-Server
- [ ] Prisma

Refer to [better sqlite](https://github.com/JoshuaWise/better-sqlite3)

**Comment by achou11** [comment]
Closed via https://github.com/digidem/mapeo-mapserver/pull/16
